# Generated by Django 5.1.2 on 2024-12-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password2',
        ),
    ]
