# Generated by Django 5.1.2 on 2024-12-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0002_rename_password1_registration_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='studying_techniques',
        ),
    ]
