# Generated by Django 5.1.4 on 2024-12-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0003_remove_registration_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('resting_bp', models.IntegerField()),
                ('maximum_htr', models.IntegerField()),
                ('chest_pain', models.CharField(max_length=50)),
                ('fasting_bs', models.CharField(max_length=20)),
                ('exersise_ia', models.CharField(max_length=20)),
                ('cholesterol', models.IntegerField()),
                ('resting_elr', models.CharField(max_length=150)),
                ('st_depression', models.IntegerField()),
                ('slop_peak_exercise', models.CharField(max_length=150)),
            ],
        ),
    ]
